{{- if .Values.hpa.enabled -}}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "standard-application.fullname" . }}-hpa
  namespace: {{ include "standard-application.namespace" . }}
  labels:
    {{ include "standard-application.labels" . | nindent 4 }}
  {{- if .Values.hpa.annotations }}
  annotations:
    {{ toYaml .Values.hpa.annotations | nindent 4}}
  {{- end }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "standard-application.fullname" . }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ .Values.hpa.metrics.targetCpuAverageUtilization }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ .Values.hpa.metrics.targetMemoryAverageUtilization }}
{{- end -}}