{{- $root := . -}}

{{- if .Values.secret.enabled -}}
{{- range $secret := .Values.secret.secrets }}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $root.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $root.Release.Name }}
    app.kubernetes.io/instance: {{ $root.Release.Name }}
    app.kubernetes.io/managed-by: {{ $root.Release.Service }}
    helm.sh/chart: {{ $root.Chart.Name }}
data:
  {{- range $secret_key, $secret_val := $secret.data }}
    {{ $secret_key }}: {{ $secret_val | quote }}
  {{- end }}
{{- end }}
{{- end -}}
