apiVersion: v1
kind: Service
metadata:
  name: {{ template "standard-application.fullname" . }}
  namespace: {{ template "standard-application.namespace" . }}
  labels:
    {{ include "standard-application.labels" . | nindent 4 }} 
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ include "standard-application.name" . }}
  ports:
  {{- range $port := .Values.service.ports }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      protocol: {{ $port.protocol }}
  {{ end -}}
