apiVersion: v1
name: standard-application
version: 1.0.0
appVersion: 1.0.0
description: Standard helm chart for microservices containing commons k8s artifacts.
sources:
  - https://github.com/alveesrenan/k8s-helm-charts/standard-application
maintainers:
  - name: Renan Alves
    email: alvees.renan@gmail.com
engine: java|kotlin|nodejs